---
  - name: Update all packages to the latest version
    apt:
     upgrade: dist
    become: yes

  - name: Install Apache
    apt:
      name: apache2
      state: latest
      update_cache: yes
    become: yes

  - name: enabled mod_rewrite
    apache2_module: name=rewrite state=present
    become: yes
    notify:
      - restart apache2

  - name: Create the directory structure for site.
    file: path=/var/www/{{ item.0 }}/{{ item.1 }}/{{ item.2 }} owner=root group=root mode=0755 recurse=yes state=directory
    become: yes
    with_nested:
      - ['html']
      - ['ditelkin.com']
      - ['public_html', 'logs']

  - name: Copy Virtual Host file.
    copy:
      src: "{{ item.src }}"
      dest: "{{ item.dest }}"
      owner: root
      group: root
      mode: 0644
    become: yes
    with_items:
      - { src: 'files/ditelkin.conf', dest: '/etc/apache2/sites-available/ditelkin.conf' }
    notify:
      - restart apache2

  - name: a2dissite default site
    command: a2dissite {{ item }}
    become: yes
    with_items:
      - 000-default.conf

  - name: a2ensite our sites
    command: a2ensite {{ item }}
    become: yes
    args:
      creates: /etc/apache2/sites-enabled/{{ item }}
    with_items:
      - ditelkin.conf
    notify:
      - restart apache2

  - name: Start the service at boot
    service: name={{ item }} state=started enabled=yes
    become: yes
    with_items:
      - apache2
