---
# tasks file for wordpress
    - name: Download WordPress.
      get_url: url=https://wordpress.org/latest.tar.gz dest=/tmp/wordpress.tar.gz validate_certs=no

    - name: Extract WordPress
      unarchive: src=/tmp/wordpress.tar.gz dest=/var/www/html/ditelkin.com/public_html copy=no

    - name: Copy sample config file
      copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        owner: root
        group: root
        mode: 0644
      with_items:
        - { src: "files/wp-config.php", dest: "/var/www/html/ditelkin.com/public_html/wordpress/wp-config.php" }
      notify:
        restart apache
